#!/bin/bash

src=src
build=build
out=out
uri=https://github.com/sahlberg/fuse-nfs.git
checkout=master

root="$(realpath "$(dirname "$0")")"
parent="$(realpath "$root"/..)"

if [ -n "$FUSENFS_URI"      ]; then uri="$FUSENFS_URI"; fi
if [ -n "$FUSENFS_CHECKOUT" ]; then checkout="$FUSENFS_CHECKOUT"; fi

src="$root/$src"
build="$root/$build"
out="$root/$out"

function update {
  if [ ! -d "$src" ]
  then
    git clone --no-checkout -- "$uri" "$src"
    cd -- "$src"
  else
    cd -- "$src"
    git remote set-url origin "$uri"
    find -maxdepth 1 -not -name .git -not -name . -exec rm -rf {} \;
    git fetch
  fi
  git checkout "$checkout" >/dev/null
  git reset --hard;
  autoreconf --install
  cd -- "$root"
}

function compile {
  rm -rf -- "$build"
  mkdir -p -- "$build"
  cd -- "$build"
  chmod -w "$root"
  incs=( "${INCLUDES[@]/#/-I}" )
  libs=( "${LIBS[@]/\%ARCH\%/"$1"}" )
  libs=( "${libs[@]/#/-L}" )
  "$src"/configure --host="$1" CPPFLAGS="${incs[*]} $FLAGS" CFLAGS="${incs[*]} $FLAGS" LDFLAGS="${libs[*]}"
  make
  chmod u+w "$root"
  cd -- "$root"
  mkdir -p "$out/$1"
  cp "$build"/fuse/$2 "$out/$1"
}

set -ex

chmod u+w "$root"

rm -rf -- "$out"
mkdir -p -- "$out"

"$parent"/libnfs/mkbuild
"$parent"/dokany/mkbuild

update

INCLUDES=( "$parent"/libnfs/src/include/ )
LIBS=( "$parent"/libnfs/out/%ARCH%/ )

compile "x86_64" fuse-nfs

FLAGS=" -static -static-libgcc -static-libstdc++ -pthread -l:libpthread.a"
LIBS+=( "$parent"/dokany/out/%ARCH%/ )
INCLUDES+=( "$parent"/dokany/src/dokan_fuse/include/ )

compile "i686-w64-mingw32" fuse-nfs.exe
compile "x86_64-w64-mingw32" fuse-nfs.exe
