#!/bin/bash

src=src
build=build
out=out
uri=https://github.com/dokan-dev/dokany.git
checkout=origin/master

root="$(realpath "$(dirname "$0")")"

if [ -n "$DOKANY_URI"      ]; then uri="$DOKANY_URI"; fi
if [ -n "$DOKANY_CHECKOUT" ]; then checkout="$DOKANY_CHECKOUT"; fi

src="$root/$src"
build="$root/$build"
out="$root/$out"

function update {
  if [ ! -d "$src" ]
  then
    git clone --no-checkout -- "$uri" "$src"
    cd -- "$src"
  else
    cd -- "$src"
    git remote set-url origin "$uri"
    find -maxdepth 1 -not -name .git -not -name . -exec rm -rf {} \;
    git fetch
  fi
  git checkout "$checkout" >/dev/null
  git reset --hard;
  cd -- "$root"
}

function compile {
  rm -rf -- "$build"
  mkdir -p -- "$build"
  cd -- "$build"
  chmod -w "$root"
  cmake -DCMAKE_TOOLCHAIN_FILE="$root/toolchain/$1.cmake" "$src"/dokan_fuse/
  make
  chmod u+w "$root"
  mkdir -p "$out/$1"
  cp "$build"/libdokanfuse?.dll{,.a} "$out/$1/"
  cd -- "$root"
}

set -ex

chmod u+w "$root"

rm -rf -- "$out"
mkdir -p -- "$out"

update

if [ "$1" = "update" ]
  then exit 0
fi

compile i686-w64-mingw32
compile x86_64-w64-mingw32
